apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastapi

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml

images:
  - name: ghcr.io/atlantik4790/04-python-fastapi
    newTag: REPLACE_WITH_SHA

